version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-db
    restart: always
    expose:
      - '5432'
    ports:
      - '5432:5432'
    networks:
      - app-tier
    environment:
      POSTGRES_DB: mynestapp
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpwd
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - app-tier
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mynestapp
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpwd
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
    driver: local
