version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-db
    restart: always
    expose:
      - '${POSTGRES_PORT}'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      - app-tier
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${NESTJS_PORT}:${NESTJS_PORT}'
    depends_on:
      - postgres
    networks:
      - app-tier
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
    driver: local
